#See README.md for detailed explaination of each option and what it does

wormBehavior:
  wormType: Simplexworm
  
  #Amount of octaves in simplex function determining worm movement
  xMovementOctaveCount: 3
  yMovementOctaveCount: 3
  zMovementOctaveCount: 3
  
  #Amplitudes for Simplex functions determining worm movement
  xSpreadAmplitude: 2.0
  ySpreadAmpltitude: 2.0
  zSpreadAmpltitude: 2.0
  
  #Threshhold inside which the worm wont move
  xSpreadThreshHold: 0.0
  ySpreadThreshHold: 0.05
  zSpreadThreshHold: 0.0
  
  #Frequency for Simplex functions determining worm movement
  xSpreadFrequency: 0.08
  ySpreadFrequency: 0.06
  zSpreadFrequency: 0.08
  
  #Seed used for Simplex generator to calculate movement in each dimension, -1 for random seed
  xSeed: -1
  ySeed: -1
  zSeed: -1

caveFormingBehavior:
  formingType: SimplexSphere
  
  #Lower bound of the range in which all blocks in the given direction are cleared around the center cave block
  xLowerRadiusBound: 2
  yLowerRadiusBound: 2
  zLowerRadiusBound: 2
  
  #Lower bound of the range in which all blocks in the given direction are cleared around the center cave block
  xUpperRadiusBound: 6
  yUpperRadiusBound: 6
  zUpperRadiusBound: 6
  
  #Frequency of the Simplex function determining the range in which all blocks in the given direction are cleared around the center cave block
  xFrequency: 0.1
  yFrequency: 0.1
  zFrequency: 0.1
  
  #Amount of octaves of the Simplex function determining the range in which all blocks in the given direction are cleared around the center cave block
  xOctaves: 3
  yOctaves: 3
  zOctaves: 3
  
  #Additional slices besides the main one which will be cleared out in each 2 dimensional level
  xzSlices: 0
  xySlices: 0
  yzSlices: 0
  
  #Materials that wont be replaced when generating caves, use spigot material identifiers here
  ignoreMaterials:
   - BEDROCK
  
  #Seed used for the generator determining spread for each dimension, -1 for random seed
  xSeed: -1
  ySeed: -1
  zSeed: -1
  
  #Material with which the emptied out space is replaced, use identifiers as specified here:
  #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html   (Default: AIR)
  fillMaterial: AIR
  
  #Whether spoofed block breaks are sent to hidden ore when removing blocks
  useHiddenOre: true
 
distribution:
  area:
    type: ELLIPSE
    world: abydos
    center:
      x: 0
      z: 0
    xSize: 500
    zSize: 500
  lowerYBound: 0
  upperYBound: 255
  minimumSurfaceDistance: 6
  seedChance: 0.03
  lowerCaveLengthBound: 50
  upperCaveLengthBound: 250
  yScanIgnoreMaterials:
   - LEAVES
   - LEAVES_2
   - LOG
   - LOG_2
   - STATIONARY_WATER
   - WATER
   - CACTUS
   - SUGAR_CANE_BLOCK
   - MELON
   - PUMPKIN
   - MUSHROOM
   - GRASS
   - RED_MUSHROOM
   - LONG_GRASS
  minimumCaveLength: 30
  caveSystems:
    a:
      chance: 0.1
      offSets:
        a:
          xOffSet: 1
          yOffSet: 0
          zOffSet: 1
        b:
          xOffSet: -1
          yOffSet: 0
          zOffSet: 1
        c:
          xOffSet: -1
          yOffSet: 1
          zOffSet: -1
    # b:
      # chance: 0.1
      # offSets:
        # a:
          # xOffSet: 2
          # yOffSet: 1
          # zOffSet: 2
        # b:
          # xOffSet: -2
          # yOffSet: -2
          # zOffSet: -2
        # c:
          # xOffSet: 2
          # yOffSet: -1
          # zOffSet: 3
        # d:
          # xOffSet: 1
          # yOffSet: 0
          # zOffSet: 1
    # c:
      # chance: 0.1
      # offSets:
        # a:
          # xOffSet: 1
          # yOffSet: 0
          # zOffSet: 1
        # b:
          # xOffSet: -1
          # yOffSet: 0
          # zOffSet: 1
    # d:
      # chance: 0.1
      # offSets:
        # a:
          # xOffSet: 1
          # yOffSet: 0
          # zOffSet: -2
          
  caveSystemSeed: -1
  seed: -1