#See README.md for detailed explaination of each option and what it does

wormBehavior:
  wormType: Simplexworm
  
  #Amount of octaves in simplex function determining worm movement
  xMovementOctaveCount: 3
  yMovementOctaveCount: 3
  zMovementOctaveCount: 3
  
  #Amplitudes for Simplex functions determining worm movement
  xSpreadAmplitude: 2.0
  zSpreadAmplitude: 2.0
  xSpreadAmplitude: 2.0
  
  #Threshhold inside which the worm wont move
  xSpreadThreshHold: 0.05
  ySpreadThreshHold: 0.05
  zSpreadThreshHold: 0.05
  
  #Frequency for Simplex functions determining worm movement
  xSpreadFrequency: 0.1
  ySpreadFrequency: 0.1
  zSpreadFrequency: 0.1
  
  #Seed used for Simplex generator to calculate movement in each dimension, -1 for random seed
  xSeed: -1
  ySeed: -1
  zSeed: -1

caveFormingBehavior:
  formingType: SimplexSphere
  
  #Lower bound of the range in which all blocks in the given direction are cleared around the center cave block
  xLowerRadiusBound: 2
  yLowerRadiusBound: 2
  zLowerRadiusBound: 2
  
  #Lower bound of the range in which all blocks in the given direction are cleared around the center cave block
  xUpperRadiusBound: 6
  yUpperRadiusBound: 6
  zUpperRadiusBound: 6
  
  #Frequency of the Simplex function determining the range in which all blocks in the given direction are cleared around the center cave block
  xFrequency: 0.1
  yFrequency: 0.1
  xFrequency: 0.1
  
  #Amount of octaves of the Simplex function determining the range in which all blocks in the given direction are cleared around the center cave block
  xOctaves: 3
  yOctaves: 3
  zOctaves: 3
  
  #Seed used for the generator determining spread for each dimension, -1 for random seed
  xSeed: -1
  ySeed: -1
  zSeed: -1
  
  #Material with which the emptied out space is replaced, use identifiers as specified here:
  #https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html   (Default: AIR)
  fillMaterial: AIR