name: ${project.name}
main: com.github.maxopoly.caveworm.Caveworm
author: Maxopoly
version: ${project.version}
depend: [CivModCore]
commands:
    cwgen:
      permission: cw.op
    cwreload:
      permission: cw.op
permissions:
    cw.op:
        default: op